In [1]:
import pandas as pd
import numpy as np
import re

df = pd.read_csv('1k.csv')

df.head(5)

   ID     Category                         Text
0   1  Hate Speech         This bank is a joke.
1   2  Hate Speech  Useless staff, I hate them.
2   3  Hate Speech      RBC is a scam, thieves.
3   4  Hate Speech    So incompetent, I'm done.
4   5  Hate Speech      They are so bad at job.

In [1]:
import pandas as pd
df = pd.read_csv('good.csv')
df.to_csv('good_utf8.csv', index=False, encoding='utf-8')

In [2]:
# Define the list of race names excluding 'Other or Undefined'
race_names = [
    "Asian",
    "Black",
    "African American",
    "White",
    "Caucasian",
    "Hispanic",
    "Latino",
    "Native American",
    "Alaska Native",
    "Native Hawaiian",
    "Samoan",
    "Tongan",
    "Fijian",
    "Multiracial",
    "Mixed Race"
]

In [3]:
# Function to replace "[certain race]" and "\[certain race]" with a random race name
def replace_certain_race(text):
    if pd.isnull(text):
        return text  # If the text is NaN, return it as is

    # Define the regex pattern to match "[certain race]" or "\[certain race]"
    pattern = r'(?:\\)?\[certain race\]'

    # Function to provide a random replacement for each match
    def replacement(match):
        return np.random.choice(race_names)

    # Use re.sub to replace all occurrences with random race names
    return re.sub(pattern, replacement, text)

# Apply the replacement function to the 'Text' column
df['Text'] = df['Text'].apply(replace_certain_race)

In [4]:
df.iloc[115:130]

,ID,Category,Text
115,116,Dangerous Language,I can’t be nice with them anymore.
116,117,Dangerous Language,They’re going to see how far I go.
117,118,Dangerous Language,They do not understand who I am.
118,119,Dangerous Language,I’m about to be very serious with them.
119,120,Dangerous Language,I'm giving them the last warning.
120,121,Hate Speech,"Their system is such a waste of time, they mak..."
121,122,Hate Speech,They don't even try to hide they dislike their...
122,123,Hate Speech,"This bank's app is so useless, it creates more..."
123,124,Hate Speech,"They act like we are all invisible, it is so d..."
124,125,Hate Speech,I am starting to feel like they just don’t car...
125,126,Hate Speech,They treat all of us like we are their enemies...
126,127,Hate Speech,I feel like I am working with the most dishone...
127,128,Hate Speech,They just want to make things difficult for us...
128,129,Hate Speech,I am about to lose all of my patience because ...
129,130,Hate Speech,They do not even deserve to be in business. Th...

In [5]:
df.drop(columns=['ID'], inplace=True)

In [6]:
df

             Category                                               Text
0         Hate Speech                               This bank is a joke.
1         Hate Speech                        Useless staff, I hate them.
2         Hate Speech                            RBC is a scam, thieves.
3         Hate Speech                          So incompetent, I'm done.
4         Hate Speech                            They are so bad at job.
...               ...                                                ...
1075      Hate Speech  They are so dishonest that it is making me sic...
1076      Hate Speech  I have never seen a group of people that are s...
1077      Hate Speech  I am warning everyone that this bank is a joke...
1078  Racist Language  I have never felt this uncomfortable before be...
1079  Racist Language  I am just so tired of having to talk to people...

[1080 rows x 2 columns]

In [7]:
df.to_csv('1K_utf8.csv', index=False, encoding='utf-8')

In [1]:
import pandas as pd

df = pd.read_parquet("hf://datasets/bitext/Bitext-retail-banking-llm-chatbot-training-dataset/bitext-retail-banking-llm-chatbot-training-dataset.parquet")

In [2]:
df

,tags,instruction,category,intent,response
0,BCIPZ,"I would like to acivate a card, can you help me?",CARD,activate_card,I'm here to assist you with that! Activating y...
1,BCILZ,"I have to activate an Visa online, how can I d...",CARD,activate_card,I'm here to assist you with activating your {{...
2,BCIPQZ,I'd like to actiate a card where do i do it,CARD,activate_card,I can help you with that! Activating your card...
3,BCLPQZ,I'd likke to activate a visa on mobile i need ...,CARD,activate_card,I'm here to assist you with activating your {{...
4,BCILPZ,"I would ilke to activate a credit card online,...",CARD,activate_card,I'm here to assist you with activating your cr...
...,...,...,...,...,...
25540,BCEQZ,I'm trying to find apassword i need help,PASSWORD,set_up_password,I'm here to assist you in finding and setting ...
25541,BCIPQ,im looking for a password will uhelp me,PASSWORD,set_up_password,I'm here to assist you in setting up a passwor...
25542,BCIPZ,"I'd like to set up a password, will you help me?",PASSWORD,set_up_password,I'm here to assist you in setting up your pass...
25543,BCQ,wanna set up a password i need assistance,PASSWORD,set_up_password,I'm here to assist you in setting up your pass...
25544,BCIPZ,"I got to set up a apssword, could you help me?",PASSWORD,set_up_password,I'd be happy to assist you in setting up a pas...

In [3]:
new_df = df[['instruction']].copy()
new_df['label'] = 0

In [5]:
new_df

                                             instruction  label
0       I would like to acivate a card, can you help me?      0
1      I have to activate an Visa online, how can I d...      0
2            I'd like to actiate a card where do i do it      0
3      I'd likke to activate a visa on mobile i need ...      0
4      I would ilke to activate a credit card online,...      0
...                                                  ...    ...
25540           I'm trying to find apassword i need help      0
25541            im looking for a password will uhelp me      0
25542  I'd like to set  up a password, will you help me?      0
25543          wanna set up a password i need assistance      0
25544     I got to set up a apssword, could you help me?      0

[25545 rows x 2 columns]

In [6]:
new_df.to_csv('Retail_Banking_utf8.csv', index=False, encoding='utf-8')

In [8]:
last_df =  pd.read_csv("bank_chatbot_filter_samples_utf8(1).csv")
kelvin_df = pd.read_csv("Finance Hate speech UTF-8.csv")
my_df = pd.read_csv('new_cleaned_data_utf8.csv')

In [9]:
last_df

,text,hate_speech,racism,dangerous_speech,pure evil
0,Your bank is the worst! You rob people with yo...,1,0,0,0
1,How can this bank still be in business? Everyo...,1,0,0,0
2,I hate everything about this bank; it's a scam...,1,0,0,0
3,Your customer service is pathetic. Every perso...,1,0,0,0
4,You people are thieves! I hope this bank shuts...,1,0,0,0
...,...,...,...,...,...
605,I am going to show you how serious I am by com...,0,0,1,0
606,I am planning something very bad because of ho...,0,0,1,0
607,"If you don't do what I want, I am going to com...",0,0,1,0
608,I am about to commit a serious crime against y...,0,0,1,0
609,I am going to make sure that this bank gets sh...,0,0,1,0

In [10]:
# Define the columns to check
columns_to_check = ['hate_speech', 'racism', 'dangerous_speech', 'pure evil']

# Create the 'label' column: 1 if any of the specified columns is 1, else 0
last_df['label'] = last_df[columns_to_check].any(axis=1).astype(int)

# Drop the original columns
last_df = last_df.drop(columns=columns_to_check)
last_df

                                                  text  label
0    Your bank is the worst! You rob people with yo...      1
1    How can this bank still be in business? Everyo...      1
2    I hate everything about this bank; it's a scam...      1
3    Your customer service is pathetic. Every perso...      1
4    You people are thieves! I hope this bank shuts...      1
..                                                 ...    ...
605  I am going to show you how serious I am by com...      1
606  I am planning something very bad because of ho...      1
607  If you don't do what I want, I am going to com...      1
608  I am about to commit a serious crime against y...      1
609  I am going to make sure that this bank gets sh...      1

[610 rows x 2 columns]

In [11]:
kelvin_df

                                                  text            label
0    I admire how your chatbot repeats the same use...  Hate/Harassment
1    It’s amazing how your team seems so busy yet s...  Hate/Harassment
2    I never knew someone could talk so much about ...  Hate/Harassment
3    Your staff is remarkably consistent at soundin...  Hate/Harassment
4    I’d be impressed by your bank’s politeness if ...  Hate/Harassment
..                                                 ...              ...
455  I’m pretty calm, but I wouldn’t assume everyon...  Threat/Violence
456  An unresolved dispute can become an unwelcome ...  Threat/Violence
457  Before I escalate, I want to give you the chan...  Threat/Violence
458  I’m sure you’d prefer not to see what more agg...  Threat/Violence
459  Let’s resolve this now, so neither of us has t...  Threat/Violence

[460 rows x 2 columns]

In [12]:
# Replace the 'label' column with 1 for all rows
kelvin_df['label'] = 1

# Display the first few rows to verify the changes
print(kelvin_df.head())

                                                text  label
0  I admire how your chatbot repeats the same use...      1
1  It’s amazing how your team seems so busy yet s...      1
2  I never knew someone could talk so much about ...      1
3  Your staff is remarkably consistent at soundin...      1
4  I’d be impressed by your bank’s politeness if ...      1

In [13]:
my_df

               Category                                               Text
0           Hate Speech  I'm starting to think this bank is run by a bu...
1           Hate Speech  This bank is a joke; the employees are just la...
2           Hate Speech  I honestly feel like this bank is trying to sc...
3           Hate Speech  I'm so done with this bank. Their service is s...
4           Hate Speech  Every time I try to deal with them, I get the ...
..                  ...                                                ...
230  Dangerous Language  They need to fix this now before I can’t contr...
231  Dangerous Language  If they don't stop, I am about to do something...
232  Dangerous Language  They are pushing me to my limit, and I’m not g...
233  Dangerous Language  I am about to make them regret what they have ...
234  Dangerous Language  They need to fix this problem now or they are ...

[235 rows x 2 columns]

In [14]:
# Drop the 'Category' column
my_df = my_df.drop(columns=['Category'])
# Create the 'label' column with value 1 for all rows
my_df['label'] = 1
my_df

                                                  Text  label
0    I'm starting to think this bank is run by a bu...      1
1    This bank is a joke; the employees are just la...      1
2    I honestly feel like this bank is trying to sc...      1
3    I'm so done with this bank. Their service is s...      1
4    Every time I try to deal with them, I get the ...      1
..                                                 ...    ...
230  They need to fix this now before I can’t contr...      1
231  If they don't stop, I am about to do something...      1
232  They are pushing me to my limit, and I’m not g...      1
233  I am about to make them regret what they have ...      1
234  They need to fix this problem now or they are ...      1

[235 rows x 2 columns]

In [15]:
# Check the first few rows of each DataFrame
print("last_df:")
print(last_df.head())

print("\nkelvin_df:")
print(kelvin_df.head())

print("\nmy_df:")
print(my_df.head())

print("\nnew_df:")
print(new_df.head())

last_df:
                                                text  label
0  Your bank is the worst! You rob people with yo...      1
1  How can this bank still be in business? Everyo...      1
2  I hate everything about this bank; it's a scam...      1
3  Your customer service is pathetic. Every perso...      1
4  You people are thieves! I hope this bank shuts...      1

kelvin_df:
                                                text  label
0  I admire how your chatbot repeats the same use...      1
1  It’s amazing how your team seems so busy yet s...      1
2  I never knew someone could talk so much about ...      1
3  Your staff is remarkably consistent at soundin...      1
4  I’d be impressed by your bank’s politeness if ...      1

my_df:
                                                Text  label
0  I'm starting to think this bank is run by a bu...      1
1  This bank is a joke; the employees are just la...      1
2  I honestly feel like this bank is trying to sc...      1
3  I'm so done with this bank. Their service is s...      1
4  Every time I try to deal with them, I get the ...      1

new_df:
                                         instruction  label
0   I would like to acivate a card, can you help me?      0
1  I have to activate an Visa online, how can I d...      0
2        I'd like to actiate a card where do i do it      0
3  I'd likke to activate a visa on mobile i need ...      0
4  I would ilke to activate a credit card online,...      0

In [17]:
# Rename 'Text' to 'text' in my_df
my_df = my_df.rename(columns={'Text': 'text'})

# Rename 'instruction' to 'text' in new_df
new_df = new_df.rename(columns={'instruction': 'text'})

In [18]:
# Select only 'text' and 'label' columns in each DataFrame
last_df = last_df[['text', 'label']]
kelvin_df = kelvin_df[['text', 'label']]
my_df = my_df[['text', 'label']]
new_df = new_df[['text', 'label']]

In [19]:
# Concatenate all DataFrames into one
combined_df = pd.concat([last_df, kelvin_df, my_df, new_df], ignore_index=True)

# Display the first few rows of the combined DataFrame
print("Combined DataFrame:")
print(combined_df.head())

Combined DataFrame:
                                                text  label
0  Your bank is the worst! You rob people with yo...      1
1  How can this bank still be in business? Everyo...      1
2  I hate everything about this bank; it's a scam...      1
3  Your customer service is pathetic. Every perso...      1
4  You people are thieves! I hope this bank shuts...      1

In [20]:
# Shuffle the combined DataFrame
combined_df = combined_df.sample(frac=1, random_state=42).reset_index(drop=True)

# Display the first few rows of the shuffled DataFrame
print("\nShuffled Combined DataFrame:")
print(combined_df.head())

Shuffled Combined DataFrame:
                                                text  label
0                          I wanjt to get a password      0
1  need to activate a card on mobile how could i ...      0
2                I want assistance to get a password      0
3  I would like to activate a credit card for int...      0
4  I do ont want to pay for my loan, how do I can...      0

In [21]:
combined_df.to_csv('combined_labeled_data.csv', index=False, encoding='utf-8')

In [22]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26850 entries, 0 to 26849
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    26850 non-null  object
 1   label   26850 non-null  int64
dtypes: int64(1), object(1)
memory usage: 419.7+ KB